require "user.options"
require "user.keymaps"
require "user.autocmds"
require "user.launch"
require "user.icons"

spec "user.colorscheme"
spec "user.nvimtree"
spec "user.whichkey"
spec "user.devicons"
spec "user.mason"
spec "user.lspconfig"
spec "user.jabs"
spec "user.barbar"
spec "user.treesitter"
spec "user.completion"
spec "user.telescope"
spec "user.null-ls"
spec "user.lualine"
-- spec "user.rustacean"
spec "user.comment"
spec "user.outline"
spec "user.autopairs"
spec "user.cursorline"
spec "user.neoscroll"
spec "user.tmux"
spec "user.indentline"
spec "user.codesnap"
spec "user.diffview"
spec "user.gitsigns"
spec "user.neogit"
spec "user.dashboard"

require "user.lazy"
