require "user.options"
require "user.keymaps"
require "user.launch"

spec "user.colorscheme"
spec "user.nvimtree"
spec "user.whichkey"
spec "user.devicons"
spec "user.mason"
spec "user.lspconfig"
spec "user.jabs"
spec "user.barbar"
spec "user.treesitter"
spec "user.completion"
spec "user.telescope"
spec "user.null-ls"
spec "user.lualine"
spec "user.rustacean"
spec "user.comment"
spec "user.outline"
spec "user.autopairs"
spec "user.cursorline"
spec "user.neoscroll"

require "user.lazy"
